# Generated by Django 5.2.1 on 2025-05-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
    ]
